name: Botania_249v2
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        if: always()
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
