name: Botania_249v2
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        if: always()
        uses: actions/setup-java@v2
        with:
          java-version: '6'
          distribution: 'zulu'
      
      - name: Build with Gradle
        run: ./gradlew build -Dhttps.protocols=TLSv1.1
            

