name: Botania_249v2
on: [push]
jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
    if: always()
    uses: actions/setup-java@v2
    with:
      java-version: '7'
      distribution: 'zulu'
    arguments: 
        -Dmaven.wagon.http.ssl.insecure=true 
        -Dmaven.wagon.http.ssl.allowall=true
      
    - name: Build with Gradle
    run: ./gradlew build
